### ISSUE TITLE
Looking forward!

### ISSUE THREAD

**Issue by juanj** [fguchelaar/AdventOfCode2020#1]
Hey, just want to say that so far it has been great seeing your solutions. On the previous days I always came here after just finishing the day challenge to see your solution.
Even if you are not up to the current day with the solutions I'm still looking forward to seeing them!
Keep it up! 💪

(Feel free to close this issue)

**Comment by fguchelaar** [comment]
Thanks so much! That's very kind of you. 

I'm falling behind, because last Friday we got the keys to our new house! So it's mainly manual labor the last days. Hopefully I'll be able to return to AoC soon 🎄🎄
